[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_blog_anchor = "bhB5FcRMygdF3FS65442s7pfmyG3YcSYxEVUYiKMHis"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sujoynath/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
